### ISSUE TITLE
get_reference_sl() throws an error 

### ISSUE THREAD

**Issue by Rejoicet** [mcuttler/CoastSat.islands#1]
While running _settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)_ from the coastsat.islands code, it throws the below attribute error.
AttributeError : 'FigureManagerBase' object has no attribut 'window'

I was able to fix the issue by adding _matplotlib.use("Qt5Agg")_ under the function just before plotting the figure.

**Comment by mcuttler** [comment]
thanks for raising this @Rejoicet 
were you running the code through spyder? if so, I think this may be related to default graphics settings in spyder and one potential other fix is to go to tools>preferences>IPython console>graphics tab and set graphics backend to automatic

**Comment by kvos** [comment]
I also added that command `matplotlib.use("Qt5Agg")` at the start of the jupyter notebook in the main coastsat toolbox, probably good to add it also here

**Comment by Rejoicet** [comment]
> thanks for raising this @Rejoicet
> were you running the code through spyder? if so, I think this may be related to default graphics settings in spyder and one potential other fix is to go to tools>preferences>IPython console>graphics tab and set graphics backend to automatic

Hi, I was running it on Jupyter. I will close this issue and thank you for this amazing tool!

**Comment by 8painkiller8** [comment]
I am running the code on Spyder and I am still facing the same issue, would you mind sharing your code that has the solution to the overflow error
