### ISSUE TITLE
Issue running coastsat.islands batch contour detection

### ISSUE THREAD

**Issue by abmikkelsen** [mcuttler/CoastSat.islands#4]
Hi, 
I have an issues running the example notebook I have not been able to resolve: coastsat runs fine, but the example .ipynb in coastsat.islands gives an error when running SDS_islands.extract_sand_poly (batch contour detection)

For the coastsat.islands setup I have copied the classification folder from coastsat-master into coastsat.islands and updated the joblib import in the shoreline.py and islands.py script.  

I can't figure out if it's not creating the contours correct or If I am missing something else. 
Thank you so much, and thanks for this cool work.

**Batch contour detection**
CELL
%matplotlib qt
output = SDS_islands.extract_sand_poly(metadata, settings)

OUTPUT
Mapping shorelines:
S2:   8%
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18888\1560753613.py in <module>
      2 get_ipython().run_line_magic('matplotlib', 'qt')
      3 #output = SDS_shoreline.extract_shorelines(metadata, settings)
----> 4 output = SDS_islands.extract_sand_poly(metadata, settings)

D:\CRI\coastsat\CoastSat.islands-master\coastsat\SDS_islands.py in extract_sand_poly(metadata, settings)
    297 
    298             # process water contours into shorelines
--> 299             shoreline = SDS_shoreline.process_shoreline(contours_mwi, cloud_mask, georef, image_epsg, settings)
    300 
    301             if settings['check_detection_sand_poly']:

D:\CRI\coastsat\CoastSat.islands-master\coastsat\SDS_shoreline.py in process_shoreline(contours, cloud_mask, georef, image_epsg, settings)
    640 
    641     # convert pixel coordinates to world coordinates
--> 642     contours_world = SDS_tools.convert_pix2world(contours, georef)
    643     # convert world coordinates to desired spatial reference system
    644     contours_epsg = SDS_tools.convert_epsg(contours_world, image_epsg, settings['output_epsg'])

D:\CRI\coastsat\CoastSat.islands-master\coastsat\SDS_tools.py in convert_pix2world(points, georef)
     66 
     67     else:
---> 68         raise Exception('invalid input type')
     69 
     70     return points_converted

Exception: invalid input type

**Comment by mcuttler** [comment]
Hi @abmikkelsen. Hmm I'm not too sure. I just got a new laptop so had to do a re-install of coastsat to test this out. After a few versioning issues with different packages I was able to test the example code out. 

Unfortunately, I wasn't able to re-produce your error. 

Are you able to figure out which S2 image it is that is giving you the error?

**Comment by abmikkelsen** [comment]
Hi @mcuttler, Thank you for the response!
I just found out error is my mistake! I mixed up a script between the coastsat-master and coastsat.island-master, so the contours were not created...
Now it runs through the shoreline detection and everything works! I apologize for raising this issue. thank you for this really cool work, I am excited to run it for other small shorelines.

**Comment by mcuttler** [comment]
All good, glad it's working !
