### ISSUE TITLE
Building environmental issues

### ISSUE THREAD

**Issue by mkewsds12** [mcuttler/CoastSat.islands#7]
I ran the case program in the cosatsat environment that I installed together. But it reports an error that there is no gradual.Is this normal? Is the environment updated?Very much your work for this period！

**Comment by mkewsds12** [comment]
I change the "import gdal" to "from osgeo import gdal". Now it can run.

**Comment by mcuttler** [comment]
OK great, thanks. I think this was a small bug in one of the underlying coastsat scripts that I missed on last update. I'll push an update this afternoon.
