### ISSUE TITLE
coastsat ['reference_shoreline'] - argument 1 overflowed

### ISSUE THREAD

**Issue by 8painkiller8** [mcuttler/CoastSat.islands#8]
I am using Spyder to run the example_islands.py and whenever I try to reference_shorline (line 84 -settings['reference_shoreline'] = SDS_preprocess.get_reference_sl(metadata, settings)) an error shows as soon I select a clear image to digitize the shoreline:

OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647

**Comment by oxanarepina** [comment]
Hello, I've had the same issue. I was able to fix it in the script CoastSat.islands/coastsat/SDS_preprocess.py by changing these two lines:

`pts = ginput(n=50000, timeout=1e9, show_clicks=True)`
and
`pt_input = ginput(n=1, timeout=1e9, show_clicks=False)`,

changing `timeout=1e9` to `timeout=0`. 

I subsequently noticed in the original CoastSat repository that these lines have `timeout=-1` (i.e. in both cases the canvas "event loop" does not time out).

**Comment by 8painkiller8** [comment]
I appreciate your help tremendously! Following your suggestion, I adjusted the value from 1e9 to 0, and it worked perfectly. Your assistance has been invaluable, and I am sincerely grateful for your support!
